project:
  name: CAS
  version: 0.1.0

paths:
  out_dir: "/Volumes/work-4T/speech-rate-testing"
  bids_dir: "/Volumes/work-4T/hyperscanning-bids"
  eeg_dir: "/Volumes/work-4T/hyperscanning-testing/derived/eeg/filtered"
  annotations_dir: "/Users/hiro/PycharmProjects/hyperscanning-working/data/annotations"

environment:
  random_seed: 42